DROP DATABASE CARGO_LINE_ERD;

CREATE DATABASE CARGO_LINE_ERD;

USE CARGO_LINE_ERD;

CREATE TABLE COUNTRY (
  ID   varchar(36) NOT NULL, 
  NAME varchar(255), 
  PRIMARY KEY (ID));
  
CREATE TABLE PORT (
  PORT_ID varchar(36) NOT NULL, 
  CODE    varchar(36), 
  NAME    varchar(255), 
  COUNTRY varchar(36) NOT NULL, 
  PRIMARY KEY (PORT_ID));
  
CREATE TABLE ROUTE (
  ROUTE_ID       varchar(36) NOT NULL, 
  NAME           varchar(255), 
  SOURCE_PORT_ID varchar(36) NOT NULL, 
  DEST_PORT_ID   varchar(36) NOT NULL, 
  PRIMARY KEY (ROUTE_ID));
  
CREATE TABLE SHIP (
  SHIP_ID  varchar(36) NOT NULL, 
  NAME     varchar(255), 
  CAPACITY int(10), 
  PRIMARY KEY (SHIP_ID));
  
CREATE TABLE SHIPMENT (
  SHIPMENT_ID       varchar(36) NOT NULL, 
  CARGO_CONTENT     varchar(255), 
  TEQ_QUANTITY      int(10), 
  TOTAL_COST        double, 
  SHIP_REQUEST_DATE date, 
  NEED_BY_DATE      date, 
  STATUS            varchar(50), 
  INSURANCE_FLAG    varchar(10), 
  INSURANCE_AMOUNT  double, 
  PRIMARY KEY (SHIPMENT_ID));
  
CREATE TABLE `USER` (
  USER_ID     varchar(36) NOT NULL, 
  LOGIN_NAME  varchar(255), 
  FNAME       varchar(255), 
  LAST_NAME   varchar(255), 
  PHONE       varchar(50), 
  EMAIL       varchar(255), 
  ADDRESS     varchar(255), 
  CITY        varchar(255), 
  STATE       varchar(255), 
  POSTAL_CODE varchar(10), 
  ROLE        varchar(36), 
  PASSWORD    varchar(255), 
  COUNTRY     varchar(36) NOT NULL, 
  PRIMARY KEY (USER_ID));
  
CREATE TABLE USER_SHIPMENT (
  USER_SHIPMENT_ID varchar(36) NOT NULL, 
  USER_ID          varchar(36) NOT NULL, 
  SHIPMENT_ID      varchar(36) NOT NULL, 
  PRIMARY KEY (USER_SHIPMENT_ID, 
  USER_ID, 
  SHIPMENT_ID));
  
CREATE TABLE VOYAGE (
  VOYAGE_ID       varchar(36) NOT NULL, 
  START_DATE      date, 
  END_DATE        date, 
  VOYAGE_QUANTITY int(10), 
  COST_PER_TEQ    double, 
  ROUTE_ID        varchar(36) NOT NULL, 
  SHIP_ID         varchar(36) NOT NULL, 
  PRIMARY KEY (VOYAGE_ID));
  
CREATE TABLE VOYAGE_USER_SHIPMENT (
  VOYAGE_SHIPMENT_ID varchar(36) NOT NULL, 
  VOYAGE_ID          varchar(36) NOT NULL, 
  SHIPMENT_ID        varchar(36) NOT NULL, 
  PRIMARY KEY (VOYAGE_SHIPMENT_ID, 
  VOYAGE_ID, 
  SHIPMENT_ID));
  
ALTER TABLE PORT ADD CONSTRAINT FK_PORT_COUNTRY FOREIGN KEY (COUNTRY) REFERENCES COUNTRY (ID);
ALTER TABLE `USER` ADD CONSTRAINT FK_USER_COUNTRY FOREIGN KEY (COUNTRY) REFERENCES COUNTRY (ID);
ALTER TABLE USER_SHIPMENT ADD CONSTRAINT FK_USER_SHIPMENT_USER FOREIGN KEY (USER_ID) REFERENCES `USER` (USER_ID);
ALTER TABLE USER_SHIPMENT ADD CONSTRAINT FK_USER_SHIPMENT_SHIPMENT FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENT (SHIPMENT_ID);
ALTER TABLE VOYAGE_USER_SHIPMENT ADD CONSTRAINT FK_VOYAGE_USER_VOYAGE FOREIGN KEY (VOYAGE_ID) REFERENCES VOYAGE (VOYAGE_ID);
ALTER TABLE VOYAGE_USER_SHIPMENT ADD CONSTRAINT FK_VOYAGE_USER_SHIPMENT FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENT (SHIPMENT_ID);
ALTER TABLE VOYAGE ADD CONSTRAINT FK_VOYAGE_ROUTE FOREIGN KEY (ROUTE_ID) REFERENCES ROUTE (ROUTE_ID);
ALTER TABLE VOYAGE ADD CONSTRAINT FK_VOYAGE_SHIP FOREIGN KEY (SHIP_ID) REFERENCES SHIP (SHIP_ID);
ALTER TABLE ROUTE ADD CONSTRAINT FK_DEST_PORT FOREIGN KEY (DEST_PORT_ID) REFERENCES PORT (PORT_ID);
ALTER TABLE ROUTE ADD CONSTRAINT FK_SOURCE_PORT FOREIGN KEY (SOURCE_PORT_ID) REFERENCES PORT (PORT_ID);


